config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations'
  }

  root to: 'home#show'

  get '/about', to: 'home#show'

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :questions do
    resources :comments, module: :questions
  end

  resources :posts do
    resource :comments, module: :posts
  end

  get '*unmatched_route', to: 'home#not_found'

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_rich_text :content
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable
  before_action :authenticate_user!

  private

  def set_commentable
    @commentable = Question.find(params['question_id'])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  include UsersHelper

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.create(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
  end

  private

  def question_params
    params.require(:question).permit(
      :user_id,
      :title,
      :content
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<div class="container mx-auto m-8" style="min-height: 700px;">
  <div>
    <%= form_for @question, html: { class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" } do |f| %>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :title, 'Title:' %>
        </label>
        <%= f.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Title"%>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :content, 'Content:'%>
        </label>
        <%= f.rich_text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline h-64 overflow-scroll", placeholder: "Ask ArtsySpace how to style your new place!"%>
      </div>
      <div class="flex items-center justify-between">
        <%= f.submit "Update", class: "shadow bg-teal-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container mx-auto items-center flex-wrap pt-4 pb-12" style="min-height: 900px;">
  <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-2 py-3">
    <p class="text-3xl text-gray-800 text-center font-bold">
       Community
    </p>
    <%= link_to "Ask ArtsySpace", new_question_path, class: "bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded" %>
  </div>

  <div>
    <ul>
      <% @questions.each do |question| %>
        <li class="comments-li my-6">
          <div>
            <%= link_to user_path(question.user) do %>
              <%= user_avatar(question.user) %>
            <% end %>
            <div class="text-base inline-block ml-2">
              <%= link_to question_path(question) do %> 
                <p class="font-mono text-xl text-gray-800 text-center font-bold hover:text-teal-500">
                  <%= question.title %>
                </p>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container mx-auto m-8" style="min-height: 900px;">
  <div>
    <%= form_for @question, html: { class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" } do |f| %>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :title, 'Title:' %>
        </label>
        <%= f.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Title"%>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :content, 'Content:'%>
        </label>
        <%= f.rich_text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline h-64 overflow-scroll", placeholder: "Ask ArtsySpace how to style your new place!"%>
      </div>
      <div class="flex items-center justify-between">
        <%= f.submit "Ask!", class: "shadow bg-teal-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="py-10">
  <div class="container mx-auto my-5 min-h-screen overflow-scroll">
    <div class="flex mb-4">
      <div class="w-full bg-white">
        <div class="m-4 m-auto w-4/5">
          <p class="font-semibold mt-8">
            <time>
              <%= @question.created_at.to_formatted_s(:month_day_comma_year) %>
            </time>
          </p>
          <% if @question.user == current_user %>
            <div class="mx-auto float-right">
              <%= link_to edit_question_path(@question) do %>
                <i data-eva="edit-outline" data-eva-animation="zoom" data-eva-fill="#38b2ac" title="edit"></i>
              <% end %>
              <%= link_to @question, method: :delete, data: { confirm: 'Are you certain you want to delete this post?' } do %>
                <i data-eva="trash-2-outline" data-eva-animation="zoom" data-eva-fill="red" title="delete"></i>
              <% end %>
            </div>
          <% end %>
          <p class="font-black text-5xl"><%= @question.title %></p>
        </div>
        <div class="border-t-2 border-gray-600 text-2xl m-auto w-4/5">
          <div class="h-56 my-8">
            <%= @question.content %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render partial: 'comments/form',
    locals: { 
      commentable: @question, 
      form_styles: "border-2 w-4/5"
    }
  %>
  <%= render partial: 'comments/comments', locals: { commentable: @question } %>
</div>