config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations'
  }

  root to: 'home#show'

  get '/about', to: 'home#show'

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :questions do
    resources :comments, module: :questions
  end

  resources :posts do
    resource :comments, module: :posts
  end

  get '*unmatched_route', to: 'home#not_found'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_rich_text :description

  validates :image, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :questions
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params

    @comment.user_id = current_user.id
    @comment.save
    redirect_to @commentable, notice: 'Comment Was Created'
  end

  def edit
  end

  def update
  end

  def destroy
    @comment = Comment.find(params[:id])
    @question = @comment.commentable
    @comment.destroy!

    redirect_to question_path(@question)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UsersHelper

  def show; end

  def not_found
    render file: "#{Rails.root}/public/404.html", status: 404
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Controller for Posts
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  include UsersHelper

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.create(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(
      :user_id,
      :title,
      :location,
      :description,
      :image
    )
  end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable
  before_action :authenticate_user!

  private

  def set_commentable
    @commentable = Question.find(params['question_id'])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  include UsersHelper

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.create(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
  end

  private

  def question_params
    params.require(:question).permit(
      :user_id,
      :title,
      :content
    )
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_user_path(@user)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User Controller
class UsersController < ApplicationController
  include UsersHelper

  def show
    @user =  User.find(params[:id])
  end

  def edit
    @user =  current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :city, :bio, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# User helper to display user avatar
module UsersHelper
  AVATAR_CLOUDINARY_IMAGE_ID = 'add_wzvex8'
  AVATAR_STYLES = 'block lg:inline-block h-12 w-12 rounded-full mx-auto object-cover'
  AVATAR_ADD_ICON = 'add_wzvex8'

  def user_avatar(user)
    if user.avatar.attached?
      cl_image_tag(user.avatar.key, class: AVATAR_STYLES)
    else
      cl_image_tag(AVATAR_CLOUDINARY_IMAGE_ID, class: AVATAR_STYLES)
    end
  end
end

app/views/posts/edit.html.erb
<div class="container mx-auto m-8">

  <div class="w-full">
    <%= form_for @post, html: { class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" } do |f| %>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :title, 'Title:' %>
        </label>
        <%= f.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Title"%>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :description, 'Description:' %>
        </label>
        <%= f.rich_text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline h-64 overflow-scroll", placeholder: "Description"%>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :location, 'Location:' %>
        </label>
        <%= f.text_field :location, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Location"%>
      </div>
      <div class="mb-6 upload-btn-wrapper" id="file-upload">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
          <%= f.label :image, 'Image:' %>
        </label>
          <svg xmlns="http://www.w3.org/2000/svg" class="fill-current text-teal-500 inline-block h-12 w-12" viewBox="0 0 22 22"><path d="M19 7v2.99s-1.99.01-2 0V7h-3s.01-1.99 0-2h3V2h2v3h3v2h-3zm-3 4V8h-3V5H5c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2v-8h-3zM5 19l3-4 2 3 3-4 4 5H5z"/><path d="M0 0h24v24H0z" fill="none"/></svg>
          <%= f.file_field :image, direct_upload: true %>
        <p class="text-red-500 text-xs italic" id="file-name">Attach a file.</p>
      </div>
      <div class="flex items-center justify-between">
        <%= f.submit "Edit", class: "shadow bg-teal-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mx-auto flex content-start flex-wrap justify-start my-8" style="min-height: 900px">
  <% @posts.each do |post| %>
      <div class="xl:w-1/3 lg:w-1/3 p-2 flex block w-full">
          <div class="max-w-sm rounded overflow-hidden shadow-lg flex flex-col justify-between">
            <%= link_to post_path(post) do %>
              <%= cl_image_tag(post.image.key, :format => :jpg , class: "card-home__img object-cover") %>
            <% end %>
              <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2"><%= post.title %></div>
              </div>
              <div class="flex items-center m-4">
              <%= link_to user_path(post.user) do %>
                <%= user_avatar(post.user) %>
              <% end %>
                <div class="ml-2 text-sm">
                  <p class="text-gray-900 leading-none"><%= post.user.full_name %></p>
                  <p class="text-gray-600"><%= post.location %></p>
                </div>
              </div>
          </div>
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mx-auto m-8" style="min-height: 900px;">

  <div class="w-full">
    <%= form_for @post, html: { class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" } do |f| %>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :title, 'Title:' %>
        </label>
        <%= f.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Title"%>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :description, 'Description:' %>
        </label>
        <%= f.rich_text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline h-64", placeholder: "Description"%>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          <%= f.label :location, 'Location:' %>
        </label>
        <%= f.text_field :location, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Location"%>
      </div>
      <div class="mb-6 upload-btn-wrapper" id="file-upload">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
          <%= f.label :image, 'Image:' %>
        </label>
          <svg xmlns="http://www.w3.org/2000/svg" class="fill-current text-teal-500 inline-block h-12 w-12" viewBox="0 0 22 22"><path d="M19 7v2.99s-1.99.01-2 0V7h-3s.01-1.99 0-2h3V2h2v3h3v2h-3zm-3 4V8h-3V5H5c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2v-8h-3zM5 19l3-4 2 3 3-4 4 5H5z"/><path d="M0 0h24v24H0z" fill="none"/></svg>
          <%= f.file_field :image, direct_upload: true %>
        <p class="text-red-500 text-xs italic" id="file-name">Attach a file.</p>
      </div>
      <div class="flex items-center justify-between">
        <%= f.submit "Create", class: "shadow bg-teal-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div style="min-height: 900px">
<div class="container mx-auto bg-white rounded-lg shadow-lg mt-10 mb-10">
  <div>
    <div class="container mx-auto">
      <div class="flex flex-wrap">
        <div class="w-full md:w-8/12">
          <%= cl_image_tag @post.image.key, format: :jpg %>
        </div>
        <div class="w-full md:w-4/12 px-4 mr-auto ml-auto">
          <p class="text-sm text-gray-600 flex items-center">
           <svg class="fill-current text-gray-500 w-3 h-3 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22">
             <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/><path d="M0 0h24v24H0z" fill="none"/>
           </svg>
           <%= @post.location %>
         </p>
          <h1 class="text-5xl font-black-darker font-black">  <%= @post.title %></h1>
          <div class="text-grey-darker py-4 text-lg leading-normal overflow-scroll" style="min-height: 484px;">
            <%= @post.description %>
          </div>
            <div class="flex items-center">
              <%= link_to user_path(@post.user) do %>
                <%= user_avatar(@post.user) %>
              <% end %>

              <div class="text-sm">
                <p class="text-gray-900 leading-none"><%= @post.user.full_name %></p>
                <p class="text-gray-600"><%= @post.created_at.to_date %></p>
              </div>
            </div>
        </div>
        <div class="px-4">
          <% if @post.user == current_user %>
            <%= link_to edit_post_path(@post) do %>
              <i data-eva="edit-outline" data-eva-animation="zoom" data-eva-fill="#38b2ac" title="edit"></i>
            <% end %>
            <%= link_to @post, method: :delete, data: { confirm: 'Are you certain you want to delete this post?' } do %>
              <i data-eva="trash-2-outline" data-eva-animation="zoom" data-eva-fill="red" title="delete"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>