config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations'
  }

  root to: 'home#show'

  get '/about', to: 'home#show'

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :questions do
    resources :comments, module: :questions
  end

  resources :posts do
    resource :comments, module: :posts
  end

  get '*unmatched_route', to: 'home#not_found'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_rich_text :description

  validates :image, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :questions
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params

    @comment.user_id = current_user.id
    @comment.save
    redirect_to @commentable, notice: 'Comment Was Created'
  end

  def edit
  end

  def update
  end

  def destroy
    @comment = Comment.find(params[:id])
    @question = @comment.commentable
    @comment.destroy!

    redirect_to question_path(@question)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UsersHelper

  def show; end

  def not_found
    render file: "#{Rails.root}/public/404.html", status: 404
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Controller for Posts
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  include UsersHelper

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.create(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(
      :user_id,
      :title,
      :location,
      :description,
      :image
    )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  include UsersHelper

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.create(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
  end

  private

  def question_params
    params.require(:question).permit(
      :user_id,
      :title,
      :content
    )
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_user_path(@user)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User Controller
class UsersController < ApplicationController
  include UsersHelper

  def show
    @user =  User.find(params[:id])
  end

  def edit
    @user =  current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :city, :bio, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# User helper to display user avatar
module UsersHelper
  AVATAR_CLOUDINARY_IMAGE_ID = 'add_wzvex8'
  AVATAR_STYLES = 'block lg:inline-block h-12 w-12 rounded-full mx-auto object-cover'
  AVATAR_ADD_ICON = 'add_wzvex8'

  def user_avatar(user)
    if user.avatar.attached?
      cl_image_tag(user.avatar.key, class: AVATAR_STYLES)
    else
      cl_image_tag(AVATAR_CLOUDINARY_IMAGE_ID, class: AVATAR_STYLES)
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
      <div class="max-w-xl mx-auto rounded overflow-hidden shadow-lg">
        <%= cl_image_tag(blob.key, format: :jpg) %>
        <div class="px-6 py-4">
          <figcaption class="attachment__caption">
            <% if caption = blob.try(:caption) %>
              <%= caption %>
            <% else %>
              <div class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">
                <span class="attachment__name"><%= blob.filename %></span>
                <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
              </div>
            <% end %>
          </figcaption>
        </div>
      </div>
  <% end %>
</figure>

app/views/layouts/_footer.html.erb
<footer class="flex items-center justify-between flex-wrap bg-teal-500 p-6" style="position: relative;bottom: 0;width: 100%;">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <%= link_to root_path do %>
      <span class="font-semibold text-xl tracking-tight">🎨 ArtsySpace</span>
    <% end %>
  </div>
</footer>

app/views/layouts/_mobile_nav.html.erb
  <aside id="navigation" class="color-mid-background hidden hidden:overflowFadeInUp animated">
     <div class="p-4 animated">
       <div class="layout--wrap screen-tablet:layout--two-columns-gutter justify-center mx-auto">
         <div>
              <% if current_user != nil %>
                <%= link_to "Create Post", new_post_path, class: "block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>

                <%= link_to "Edit Profile", edit_user_path(current_user), class:"block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t"%>

                <%= link_to "Ask ArtsySpace",new_question_path , class:"block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t"%>

                <%= link_to "Community Questions", questions_path , class:"block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>

                <%= link_to "Posts", posts_path , class:"block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>

                <%= link_to "Log Out", destroy_user_session_path, class:"block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>
                <%= link_to "Create Post", new_post_path, class: "block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>

                <a href="/about" class="block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t">
                  About
                </a>

            <% else %>

                <%= link_to "LOG IN", new_user_session_path, class:"block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>

                <%= link_to "SIGN UP", new_user_registration_path, class:"block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>
                <%= link_to "Create Post", new_post_path, class: "block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t" %>

                <a href="/questions" class="block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t">
                  Community
                </a>

                <a href="/posts" class="block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t">
                  Posts
                </a>

                <a href="/about" class="block p-3 text-h4 font-normal no-underline hover:bg-secondary-pink-50t">
                  About
                </a>
            <% end %>
         </div>
       </div>
     </div>
   </aside>

app/views/layouts/_nav.html.erb
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <%= link_to root_path do %>
      <span class="font-semibold text-xl tracking-tight">🎨 ArtsySpace</span>
    <% end %>
  </div>
  <div class="block lg:hidden">
     <button data-js="toggle" aria-pressed="false" aria-expanded="false"
             aria-controls="navigation" class="text-white cursor-pointer underline font-bold" id="menu-btn">Menu</button>
  </div>
  <div id="default-nav" class="text-right align-middle w-full block flex-grow lg:flex lg:items-center lg:w-auto hidden">
    <div class="text-md lg:flex-grow">
        <%= link_to "Create Post", new_post_path, class: "bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 border-2 mr-4 rounded-sm" %>

      <a href="/questions" class="block mt-4 font-bold lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
        Community
      </a>
      <a href="/posts" class="block mt-4 font-bold lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
        Posts
      </a>
      <a href="/about" class="block mt-4 font-bold lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
        About
      </a>
      <% if current_user != nil %>
        <%= link_to user_path(current_user) do %>
          <%= user_avatar(current_user) %>
        <% end %>

        <%= render partial: 'layouts/settings', locals: { current_user: current_user } %>

      <% else %>
        <%= link_to "LOG IN", new_user_session_path, class: "block mt-4 lg:inline-block font-bold lg:mt-0 text-white hover:text-teal-200 mr-4" %>

        <%= link_to "SIGN UP", new_user_registration_path, class: "bg-purple-500 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-full" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_settings.html.erb
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.0.1/dist/alpine.js" defer></script>

<div x-data="{ open: false }" @keydown.escape="open = false" @click.away="open = false" class="relative inline-block text-left z-10">
  <div>
    <span class="rounded-md shadow-sm">
      <button @click="open = !open" type="button" class="inline-flex justify-center w-full py-2 px-4 transition ease-in-out duration-150">
        <i data-eva="menu-outline" data-eva-animation="zoom" data-eva-hover="true" data-eva-fill="white"></i>
      </button>
    </span>
  </div>
  <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg">
    <div class="rounded-md bg-white shadow-xs">
      <div class="py-1">
        <%= link_to "Edit Profile", edit_user_path(current_user), class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none fo     cus:bg-gray-100 focus:text-gray-900' %>
        <%= link_to "Ask ArtsySpace",new_question_path , class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none fo     cus:bg-gray-100 focus:text-gray-900' %>
      </div>
      <div class="border-t border-gray-100"></div>
      <div class="py-1">
        <%= link_to "Community Questions", questions_path , class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none fo     cus:bg-gray-100 focus:text-gray-900' %>
        <%= link_to "Posts", root_path , class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900' %>
      </div>
      <div class="border-t border-gray-100"></div>
      <div class="py-1">
        <%= link_to "About", '/about', class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900' %>

        <%= link_to "Log Out", destroy_user_session_path, class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900' %>

      </div>
      <div class="border-t border-gray-100"></div>
      <div class="py-1">
        <%= link_to "Delete Account",
          current_user, method: :delete,
          data: { confirm: 'Are you sure you want to delete your account?'},
          class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900'
        %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167407216-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-167407216-1');
    </script>

    <title>ArtsyDecor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all',  'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Eva icons -->
    <script src="https://unpkg.com/eva-icons"></script>

    <script src="https://cdn.jsdelivr.net/gh/CityOfNewYork/nyco-patterns-framework@v0.0.23/dist/utilities/toggle/toggle.iffe.js"></script>
    <!-- NYCO Patterns Feed -->
    <script src="https://cdn.jsdelivr.net/gh/CityOfNewYork/nyco-patterns@v2.2.3/dist/objects/feed/feed.js" type="text/javascript"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.js?features=Promise&gated=gated" type="text/javascript"></script>
      <script>
         window.onload = function () { 
           var toggle = new Toggle();
         }
      </script>

    <title>ArtsySpace | Improve your well being by decorating your room</title>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= render "layouts/mobile_nav" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <script>
      eva.replace()
    </script>
  </body>
</html>